import { getDraft } from './queries'

function markdownToHtml(md: string): string {
  return md
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\[(.+?)\]\((.+?)\)/g, '<a href="$2">$1</a>')
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
    .replace(/^---$/gm, '<hr>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<)(.+)/gm, '<p>$1</p>')
    .replace(/<p><\/p>/g, '')
}

export function exportToHtml(draftId: string): string {
  const draft = getDraft(draftId)
  if (!draft) throw new Error('草稿不存在')

  const bodyHtml = markdownToHtml(draft.content)

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${draft.title || 'AutoMedia Export'}</title>
  <style>
    body { max-width: 680px; margin: 40px auto; padding: 0 20px; font-family: -apple-system, sans-serif; line-height: 1.8; color: #333; }
    h1 { font-size: 1.8em; margin-bottom: 0.5em; }
    h2 { font-size: 1.4em; margin-top: 1.5em; }
    h3 { font-size: 1.2em; margin-top: 1.2em; }
    blockquote { border-left: 3px solid #e94560; padding-left: 16px; color: #666; margin: 1em 0; }
    hr { border: none; border-top: 1px solid #eee; margin: 2em 0; }
    a { color: #e94560; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .meta { color: #999; font-size: 0.9em; margin-bottom: 2em; }
  </style>
</head>
<body>
  <div class="meta">
    <span>平台: ${draft.platform}</span> · <span>${draft.createdAt.slice(0, 10)}</span> · <span>Generated by AutoMedia</span>
  </div>
  ${bodyHtml}
</body>
</html>`
}

export function exportToMarkdown(draftId: string): string {
  const draft = getDraft(draftId)
  if (!draft) throw new Error('草稿不存在')
  return draft.content
}
